import defaultTheme from 'tailwindcss/defaultTheme';
import forms from '@tailwindcss/forms';

/** @type {import('tailwindcss').Config} */
export default {
    content: [
        './vendor/laravel/framework/src/Illuminate/Pagination/resources/views/*.blade.php',
        './storage/framework/views/*.php',
        './resources/views/**/*.blade.php',
    ],

    darkMode: 'class', // Enable class-based dark mode

    theme: {
        extend: {
            fontFamily: {
                sans: ['Figtree', ...defaultTheme.fontFamily.sans],
            },
        },
    },

    safelist: [
        // Dark mode badge colors
        'dark:bg-sky-700',
        'dark:bg-amber-600',
        'dark:bg-red-800',
        'dark:bg-green-800',
        'dark:bg-purple-800',
        'dark:bg-orange-800',
        'dark:bg-slate-500',
        'dark:bg-slate-800',
        'dark:text-sky-100',
        'dark:text-amber-100',
        'dark:text-red-200',
        'dark:text-green-200',
        'dark:text-purple-200',
        'dark:text-orange-200',
        'dark:text-slate-100',
        // Light mode badge colors
        'bg-sky-500',
        'bg-amber-500',
        'bg-red-500',
        'bg-green-500',
        'bg-purple-500',
        'bg-orange-500',
        'bg-slate-200',
        // Slate colors for services button
        'bg-slate-600',
        'bg-slate-700',
        'hover:bg-slate-700',
        '!bg-slate-700',
        'hover:!bg-slate-700',
        'dark:bg-slate-500',
        'dark:bg-slate-600',
        'dark:hover:bg-slate-600',
        'dark:!bg-slate-500',
        'dark:!bg-slate-600',
        'dark:hover:!bg-slate-600',
        // Ensure sky colors work in dark mode
        'dark:bg-sky-500',
        'dark:bg-sky-600',
        'dark:bg-sky-700',
        'dark:bg-sky-800',
        'dark:hover:bg-sky-600',
        'dark:hover:bg-sky-700',
        'dark:hover:bg-sky-800',
        'dark:text-sky-400',
        'dark:text-sky-300',
        'dark:border-sky-600',
        'dark:ring-sky-500',
        // Gradient backgrounds for help pages
        'bg-gradient-to-r',
        'from-blue-600',
        'to-blue-700',
        'from-red-500',
        'to-red-600',
        'from-purple-500',
        'to-purple-600',
        'from-green-500',
        'to-green-600',
        'from-blue-500',
        'to-cyan-600',
        'from-slate-600',
        'to-slate-700',
        'from-emerald-500',
        'to-teal-600',
        'from-purple-500',
        'to-indigo-600',
        'from-amber-500',
        'to-amber-600',
        'from-sky-500',
        'to-sky-600',
        'from-purple-500',
        'to-pink-600',
        'from-green-500',
        'to-emerald-500',
        'from-sky-500',
        'to-blue-500',
        'from-amber-500',
        'to-orange-500',
        'from-purple-500',
        'to-pink-500',
        'from-red-500',
        'to-rose-500',
        'from-indigo-500',
        'to-purple-500',
        'from-green-500',
        'to-emerald-600',
    ],

    plugins: [forms],
};
